version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: knowledge-ai-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: knowledgeai
      POSTGRES_PASSWORD: knowledgeai
      POSTGRES_DB: knowledge_ai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
